### ISSUE TITLE
PHP Function names blank in navigation bar

### ISSUE THREAD

**Issue by mglinski** [derekr/php.sugar#17]
See: http://img527.imageshack.us/img527/3995/picture1rsv.png
-Matt

**Comment by derekr** [comment]
What version of Espresso and PHP.sugar are you using?

**Comment by mglinski** [comment]
php.sugar: Latest code as of issue posting, built in xcode using 10.5.5/Debug.
Espresso: v1.0.4

**Comment by derekr** [comment]
Fixed for 1.0b6.

**Comment by mglinski** [comment]
Issue is not fixed on 1.0b6
See attached.
http://imgur.com/G3CA.png

Using: Espresso: v1.0.4
-Matt

**Comment by donut** [comment]
[More detail on this issue](http://github.com/derekr/php.sugar/issues#issue/18).
